/*
SELECT A.TITLE, A.BOARD_ID, B.REPLY_ID, B.WRITER_ID, B.CONTENTS, B.CREATED_DATE
FROM USED_GOODS_BOARD A
INNER JOIN USED_GOODS_REPLY B ON A.BOARD_ID = B.BOARD_ID
WHERE TO_CHAR(A.CREATED_DATE, 'YYYY-MM') = '2022-10'
ORDER BY B.CREATED_DATE ASC, A.TITLE ASC;
*/

SELECT TITLE,a.BOARD_ID,b.REPLY_ID,b.WRITER_ID,b.CONTENTS,DATE_FORMAT(b.CREATED_DATE,'%Y-%m-%d') as CREATED_DATE
from USED_GOODS_BOARD as a
INNER JOIN USED_GOODS_REPLY as b
on a.BOARD_ID = B.BOARD_ID
WHERE a.CREATED_DATE LIKE '2022-10%'
order by B.CREATED_DATE ASC, TITLE ASC;