/*
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE,'%Y-%M-%D') AS PUBLISHED_DATE
FROM BOOK 
WHERE CATEGORY = '인문' AND  PUBLISHED_DATE >= '2021-01-01 00:00:00' AND PUBLISHED_DATE < '2022-01-01 00:00:00'
ORDER BY PUBLISHED_DATE ASC
*/
SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, "%Y-%m-%d") AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '인문' AND YEAR(PUBLISHED_DATE) = '2021'
ORDER BY PUBLISHED_DATE ASC;
