/*
SELECT I.INGREDIENT_TYPE , SUM(F.TOTAL_ORDER) AS TOTAL_ORDER
FROM FIRST_HALF AS F LEFT JOIN ICECREAM_INFO AS I ON I.FLAVOR = F.FLAVOR
GROUP BY INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC
*/

SELECT IC.INGREDIENT_TYPE, SUM(FI.TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_INFO IC 
INNER JOIN FIRST_HALF FI
 ON IC.FLAVOR =  FI.FLAVOR
GROUP BY IC.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER;